# Generated by Django 4.2 on 2023-05-05 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2f80076e-6fc0-42e1-b53e-6aeb1b4cdfdb"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
