# Generated by Django 4.2 on 2023-05-07 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d83a43fe-a5bd-4740-aefd-d6f17ce5015a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
