# Generated by Django 4.2 on 2023-05-08 08:57

from django.db import migrations, transaction
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    with transaction.atomic():
        call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_create_test_user"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
